#!/bin/bash

PATH_PREFIX=${1:-"/workspace/threadx_exploitation"}

OUTPUT_FILES=(
    "read_before_kom.txt"
    "read_after_kom.txt"
    "write_before_kom.txt"
    "write_after_kom.txt"
)

STM32F405_PATHS=(
    "$PATH_PREFIX/qemu_stm32f405_m4_read_before_exploit/qemu_stm32f405_m4_read_before_exploit/STM32CubeIDE/Tx_ModuleManager/Debug/Tx_ModuleManager.elf"
    "$PATH_PREFIX/qemu_stm32f405_m4_read_before_exploit/qemu_stm32f405_m4_read_before_exploit/STM32CubeIDE/Tx_Module/Debug/Tx_Module.elf"
    "$PATH_PREFIX/qemu_stm32f405_m4_read_after_exploit/qemu_stm32f405_m4_read_after_exploit/STM32CubeIDE/Tx_ModuleManager/Debug/Tx_ModuleManager.elf"
    "$PATH_PREFIX/qemu_stm32f405_m4_read_after_exploit/qemu_stm32f405_m4_read_after_exploit/STM32CubeIDE/Tx_Module/Debug/Tx_Module.elf"
    "$PATH_PREFIX/qemu_stm32f405_m4_write_before_exploit/qemu_stm32f405_m4_write_before_exploit/STM32CubeIDE/Tx_ModuleManager/Debug/Tx_ModuleManager.elf"
    "$PATH_PREFIX/qemu_stm32f405_m4_write_before_exploit/qemu_stm32f405_m4_write_before_exploit/STM32CubeIDE/Tx_Module/Debug/Tx_Module.elf"
    "$PATH_PREFIX/qemu_stm32f405_m4_write_after_exploit/qemu_stm32f405_m4_write_after_exploit/STM32CubeIDE/Tx_ModuleManager/Debug/Tx_ModuleManager.elf"
    "$PATH_PREFIX/qemu_stm32f405_m4_write_after_exploit/qemu_stm32f405_m4_write_after_exploit/STM32CubeIDE/Tx_Module/Debug/Tx_Module.elf"
)

DEVICE2=netduinoplus2
DEVICE2_DIR=$(pwd)/$DEVICE2

echo "Enter ./run_gdb.sh $PATH_PREFIX $DEVICE2 in another terminal"
qemu-system-arm -M $DEVICE2 -serial file:output.txt -cpu cortex-m4 -nographic -kernel ${STM32F405_PATHS[2]} --device loader,file=${STM32F405_PATHS[3]} -s -S 
wait
echo -e "\033[1;32mFinished running QEMU on $DEVICE2 with MPU disabled\033[0m"
echo "Press Enter to continue..."
read

mkdir -p "$DEVICE2_DIR"  
echo "Created directory: $DEVICE2_DIR"
echo -e "\033[1;32mFinished running QEMU on $DEVICE2 with MPU disabled\033[0m"
cd $DEVICE2_DIR
for i in 0 2 4 6; do
    kernel="${STM32F405_PATHS[$i]}"
    module="${STM32F405_PATHS[$i+1]}"
    output="${OUTPUT_FILES[$i/2]}"

    expect <<EOF
    spawn qemu-system-arm -M $DEVICE2 -serial file:output.txt -cpu cortex-m4 -nographic -kernel $kernel --device loader,file=$module -d int,exec,guest_errors -s -S -D $output
    expect "(qemu)" { send "c\r" } 
    after 300
    send "q\r"
    expect eof
EOF

    echo -e "\033[1;32mFinished running QEMU on $DEVICE2 $output\033[0m"
    
    if [[ "$output" == *"before"* ]]; then
        echo -e "\033[1;32mYou can find the fault information with MemManage Handler in file: $DEVICE2/$output\033[0m"
    elif [[ "$output" == *"after"* ]]; then
        echo -e "\033[1;32mKOM has been successfully launched. You can review the $output, which contains no fault information.\033[0m"
    fi

    echo "Grep Fault_Handler"
    grep "Fault_Handler" $output 
    echo "Press Enter to continue..."
    read
done
